[change] Added WireguardParser #145
openwisp/openwisp-network-topology pull request #148
Opened 2022-06-01 19:47 UTC by codesankalp

Closes #145

2022-06-01 19:48 UTC, codesankalp commented
Output:

![image](https://user-images.githubusercontent.com/56037184/171489223-0ab7ea44-551a-4838-b108-4e35565261e5.png)

fetch url: https://gist.githubusercontent.com/codesankalp/25286e0ff8b4750270824f94c1edbc02/raw/86ca6bffb8daf530331693df375e2a80ff2d4209/wireguard-conf

2022-06-06 16:18 UTC, nemesisdesign requested changes
https://github.com/openwisp/openwisp-network-topology#available-features needs to be updated

2022-06-27 22:41 UTC, nemesisdesign approved these changes

2022-06-28 22:04 UTC, nemesisdesign approved these changes

2022-06-28 22:05 UTC, merged